export const fallbackTrack = {
  id: 'demo-code-red',
  sort_order: 1,
  title: 'CODE RED',
  audio_file_name: 'code-red.mp3',
  audio_url: '/audio/reclamation/code-red.mp3',
  act: 'ACT THREE',
  act_keys: ['Override obstruction', 'Reclaim the route', 'Expose the system'],
  shell_image: '/images/reclamation/shells/act-three-shell.png',
  shell_image_url: '/images/reclamation/shells/act-three-shell.png',
  visual_mode: 'system-fracture',
  primary_color: '#ff1a2d',
  intensity: 95,
  display_text: 'Power through exposure.',
  needs_user_input: '',
  notes: 'Demo fallback track.',
  is_active: true,
  act_logo_image: '/images/reclamation/logos/reclamation-act-three-logo.png',
  act_logo_text: 'CHROMA KEY PROTOCOL',
  act_logo_subtitle: 'ACT THREE',
  act_logo_ring_enabled: true,
  act_logo_reactivity_strength: 90,
  act_logo_glow_strength: 95,
  act_logo_rotation_speed: 0.15,
  act_logo_visualizer_style: 'radial-bars',
  background_image: '',
  background_overlay_opacity: 0.22,
  background_blur: 0,
  background_motion_enabled: true,
  scanline_enabled: true,
  glitch_level: 35,
  fog_level: 20,
  pulse_strength: 90,
  vignette_strength: 70,
  display_text_enabled: true,
  display_text_label: 'LYRICAL BANK',
  display_text_position: 'bottom-center',
  display_text_animation: 'pulse',
  display_text_size: 'large',
  display_text_weight: 'bold',
  display_text_reactive: true,
  sonic_artifact_enabled: true,
  sonic_artifact_title: 'SONIC ARTIFACT DECLARATION',
  sonic_artifact_declaration: 'The route is reclaimed.',
  sonic_artifact_position: 'upper-left',
  sonic_artifact_style: 'protocol-card',
  act_keys_enabled: true,
  act_keys_title: 'KEYS TO ACT THREE',
  act_keys_position: 'right-panel',
  act_keys_style: 'access-panel',
  release_status: 'draft',
};
