import actThreeEmblem from '../../public/emblems/act_three_emblem.gif';

export const fallbackTrack = {
  id: 'demo-code-red',
  sort_order: 1,
  title: 'WELCOME TO THE FIRE',
  duration: 247,
  audio_file_name: 'welcome_to_the_fire.mp3',
  audio_url: '/audio/reclamation/welcome_to_the_fire.mp3',
  act: 'ACT THREE',
  act_keys: ['Override obstruction', 'Reclaim the route', 'Expose the system'],
  shell_image: '/images/reclamation/shells/act-three-shell.png',
  shell_image_url: '/images/reclamation/shells/act-three-shell.png',
  act_background_image: '/images/reclamation/shells/act-three-shell.png',
  visual_mode: 'system-fracture',
  primary_color: '#ff1a2d',
  intensity: 78,
  display_text: [
    "I'm breaking the code, I'm rewriting the system",
    "The keys in my hands, I'm taking back what's mine",
    'No firewall can hold me, no gate can keep me out',
    "I'm the glitch in their plan, watch the whole thing shut down",
    'Burn down the silence, let the signal rise',
  ].join('\n'),
  needs_user_input: '',
  notes: 'Demo fallback track.',
  is_active: true,
  album_art: actThreeEmblem,
  act_logo_asset: actThreeEmblem,
  act_logo_text: 'CHROMA KEY PROTOCOL',
  act_logo_subtitle: 'ACT THREE',
  act_logo_ring_enabled: true,
  act_logo_reactivity_strength: 90,
  act_logo_glow_strength: 95,
  act_logo_rotation_speed: 0.15,
  act_logo_visualizer_style: 'radial-bars',
  background_image: '',
  background_overlay_opacity: 0.22,
  background_blur: 0,
  background_motion_enabled: true,
  scanline_enabled: true,
  glitch_level: 35,
  fog_level: 20,
  pulse_strength: 90,
  vignette_strength: 70,
  display_text_enabled: true,
  display_text_label: 'LYRICAL BANK',
  display_text_position: 'bottom-center',
  display_text_animation: 'pulse',
  display_text_size: 'large',
  display_text_weight: 'bold',
  display_text_reactive: true,
  sonic_artifact_enabled: true,
  sonic_artifact_title: 'SONIC ARTIFACT DECLARATION',
  sonic_artifact_declaration: 'The route is reclaimed.',
  sonic_artifact_position: 'upper-left',
  sonic_artifact_style: 'protocol-card',
  act_keys_enabled: true,
  act_keys_title: 'KEYS TO ACT THREE',
  act_keys_position: 'right-panel',
  act_keys_style: 'access-panel',
  release_status: 'draft',
};

export const fallbackTracks = [
  fallbackTrack,
  {
    ...fallbackTrack,
    id: 'reclamation',
    track_id: 'reclamation',
    sort_order: 2,
    title: 'RECLAMATION',
    duration: 277,
    audio_file_name: 'reclamation.mp3',
    audio_url: '/audio/act_three/reclamation.mp3',
    display_text: [
      'The signal returns through the fire',
      'Every locked gate becomes a witness',
      'Reclamation is not permission',
      'The system bends when the source remembers',
    ].join('\n'),
    notes: 'Local fallback track from R2 audio.',
  },
];
